apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xvancoa/cv2xvancoa-blood-donors-ufe
  newName: xvancoa/cv2xvancoa-blood-donors-ufe
  newTag: 1.1.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: xvancoa/cv2xvancoa-blood-donors-webapi
  newName: xvancoa/cv2xvancoa-blood-donors-webapi
  newTag: 1.1.0