apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: cv2xvancoa-blood-donors # napr. <pfx>-ambulance-wl
spec:
  title: Darcovia krvi cv2xvancoa
  description: Registrácia a správa darcov krvi (darovanie krvi a krvnej plazmy)
  authors: "Adrián Vančo" # Zadajte mená autorov
  azureLink: "https://cv2xvancoa-blood-donors.azurewebsites.net"
  frontendRepoUrl: "https://github.com/AdrianVanco/blood-donors-ufe"
  backendRepoUrl: "https://github.com/AdrianVanco/blood-donors-webapi"
  gitopsRepoUrl: "https://github.com/AdrianVanco/blood-donors-gitops"