apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: cv2xvancoa-blood-donors-ufe
spec:
  frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell
  service:
    name: cv2xvancoa-blood-donors-ufe # referencia na službu odkiaľ sa má načítať modul
  modulePath: build/cv2xvancoa-blood-donors-ufe.esm.js # cesta v rámci služby kde sa modul nachádza