apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xvancoa/cv2xvancoa-blood-donors-ufe
  newName: xvancoa/cv2xvancoa-blood-donors-ufe # {"$imagepolicy":  "wac-hospital:cv2xvancoa-blood-donors-ufe:name"}
  newTag: main.20260524.1307 # {"$imagepolicy": "wac-hospital:cv2xvancoa-blood-donors-ufe:tag"}
- name: xvancoa/cv2xvancoa-blood-donors-webapi
  newName: xvancoa/cv2xvancoa-blood-donors-webapi # {"$imagepolicy":  "wac-hospital:cv2xvancoa-blood-donors-webapi:name"}
  newTag: latest # {"$imagepolicy": "wac-hospital:cv2xvancoa-blood-donors-webapi:tag"}
